export const data = [
  {
    id: 1,
    name: "Redmi bla bla bla 1",
    src: "/public/assets/cell1.jpg",
    priceUSD: "123",
    priceCUP: "1234",
    quantity: 1,
  },
  {
    id: 2,
    name: "otro redmi xd",
    src: "/public/assets/cell2.jpg",
    priceUSD: "321",
    priceCUP: "4321",
    quantity: 1,
  },
  {
    id: 3,
    name: "Redmi bla bla bla 1",
    src: "/public/assets/cell1.jpg",
    priceUSD: "123",
    priceCUP: "1234",
    quantity: 1,
  },
  {
    id: 4,
    name: "otro redmi xd",
    src: "/public/assets/cell2.jpg",
    priceUSD: "321",
    priceCUP: "4321",
    quantity: 1,
  },
  {
    id: 5,
    name: "Redmi bla bla bla 1",
    src: "/public/assets/cell1.jpg",
    priceUSD: "123",
    priceCUP: "1234",
    quantity: 1,
  },
  {
    id: 6,
    name: "otro redmi xd",
    src: "/public/assets/cell2.jpg",
    priceUSD: "321",
    priceCUP: "4321",
    quantity: 1,
  },
];
